CC=$(GCC)
CFLAGS=-O3
GPUCC=$(HIPCC)
GPUCFLAGS=$(HIPCFLAGS)

LIBS =

# hipCOMP configuration
ifdef USE_HIPCOMP
    HIPCOMP_PATH ?= $(HIPCOMP_ROOT)
    CFLAGS += -I$(HIPCOMP_PATH)/include -DUSE_HIPCOMP
    GPUCFLAGS += -I$(HIPCOMP_PATH)/include -DUSE_HIPCOMP
    LIBS += -L$(HIPCOMP_PATH)/lib -lhipcomp -Wl,-rpath,$(HIPCOMP_PATH)/lib
endif

LIBS += $(HIPCC_LIBS) $(GCC_LIBS)
